- serial_number: 33143189
  resolution: "VGA"
  fps: 100
  depth: False
  type: "zed2i"
  side: "left"
- serial_number: 32144978
  resolution: "VGA"
  fps: 100
  depth: False
  type: "zed2i"
  side: "right"
- serial_number: 35094665
  resolution: "VGA"
  fps: 100
  depth: False
  type: "zed2i"
  side: "right"
